name: notaemato
description: itis.team

publish_to: "none"
# major.minor.patch+YYYYMMDDNN (NN - build number. flush every day)
version: 0.4.0+2021083101

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  #architecture
  provider: ^5.0.0
  stacked: ^2.1.8
  get_it: ^7.1.3
  injectable: ^1.3.0

  #analytics
  appmetrica_sdk: ^0.0.5+2

  #firebase and push
  firebase_core: ^1.3.0
  firebase_messaging: 
  flutter_local_notifications: ^6.0.0

  #database
  get_storage:
    git:
      url: "https://git.itis.team/public-projects/get_storage.git"
      ref: no-pac

  #network
  dio: ^4.0.0
  retrofit: ^2.0.0
  web_socket_channel: ^2.1.0

  #geo
  # geocoder: 
  location: ^4.3.0
  google_maps_flutter: ^2.0.6

  #widgets
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_charts: ^19.1.66+1
  cupertino_icons: ^1.0.0
  dotted_decoration: ^2.0.0
  percent_indicator: ^3.0.1
  scroll_to_index: ^2.0.0

  #features
  supercharged: ^2.0.0
  shared_preferences: ^2.0.7
  device_info: ^2.0.2
  fluttertoast: ^8.0.7
  photo_view: ^0.12.0
  share_plus: ^2.1.4
  image_picker: ^0.8.0+4
  image_cropper: ^1.4.0
  extended_masked_text: ^2.1.0
  jiffy: ^4.1.0
  logger: ^1.0.0
  url_launcher: ^6.0.3
  clipboard: ^0.1.2+8
  stacked_services: ^0.8.3
  validators: ^3.0.0
  qr_code_scanner: ^0.5.1
  double_back_to_close: ^2.0.0
  uuid: ^3.0.4
  contacts_service: ^0.6.1
  permission_handler: ^8.1.1
  equatable: ^2.0.2
  record_mp3: ^3.0.0
  assets_audio_player: ^3.0.3+3
  collection: ^1.15.0-nullsafety.4
  janus_client: ^2.1.1-beta
  # flutter_ringtone_player: 
  callkit:
    path: plugins/callkit/  
  # janus_client:
  #   git:
  #     url: "https://git.itis.team/public-projects/flutter_janus_client.git"
  #     ref: v2_dev

dev_dependencies:
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  injectable_generator: ^1.4.1
  lint: ^1.5.3
  retrofit_generator: ^2.0.0+2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/map/

flutter_intl:
  enabled: true
  main_locale: ru
  class_name: Strings
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
